version: '3'

services:

  gonini-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=goninidb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  gonini:
    image: gonini
    depends_on:
      - gonini-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=gonini-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=goninidb
      - DATABASE_PORT=3306