version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306

  gonini:
    image: gonini
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=MyAppDb
      - DATABASE_PORT=3306